Cleaned up `conf.py` file.
